POST  http://localhost:3000/message HTTP/1.1
content-type: application/json

{
  "user": "Carlos",
  "message": "Mundo"
}

###

GET  http://localhost:3000/message HTTP/1.1
content-type: application/json

###

PUT http://localhost:3000/message HTTP/1.1
content-type: application/json

{
    "text": "Hola Mundo"
}

###

PATCH http://localhost:3000/message/640a7938ab2699d73faaf10f HTTP/1.1
content-type: application/json

{
  "message": "Hola"
}

###
POST  http://localhost:3000/message HTTP/1.1
content-type: application/json

{
  "user": "Jesus",
  "message": "Soy Jesus"
}

###

GET  http://localhost:3000/message?user=Carlos HTTP/1.1
content-type: application/json
###

DELETE   http://localhost:3000/message/640d11a5386d2a57b0eb1957 HTTP/1.1
content-type: application/json

###

GET  http://localhost:3000/user HTTP/1.1
content-type: application/json

###

GET  http://localhost:3000/user?user=Carlos HTTP/1.1
content-type: application/json

###
POST  http://localhost:3000/user HTTP/1.1
content-type: application/json

{
  "name": "Jesus"
}

###
POST  http://localhost:3000/message HTTP/1.1
content-type: application/json

{
  "user": "640e2c69fbafa296ba8ca777",
  "message": "Entidades De Jesus"
}
